In [70]:
import tensorflow as tf

#range is used to create a range of 10 numbers starting with 0
dataset = tf.data.Dataset.range(10)
#window(sise of window, stride= skip by x, shift=next line should skip the range by y, drop_remainder will drop window size less than 5)
dataset = dataset.window(5,shift=1, stride=1, drop_remainder=True)




In [71]:
#Print the set of 5 as numpy
for values in dataset:
    for v in values:
        print(v.numpy(), end=" ")
    print()


0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [72]:
#print the datset by squashing two for loop to 1 using flat map
dataset = dataset.flat_map(lambda z: z.batch(5))
for value in dataset:
    print(value.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


### Break the dataet into features and labels.
- All values from 0.. (n-1) = features
- Last values 'n' = label

In [92]:
'''
Map is like hashmap in java key = values. Here we are defining it like this format
[0,1,2,3: 4]
'''
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, stride=1, drop_remainder=True)
dataset = dataset.flat_map(lambda z: z.batch(5))
dataset = dataset.map(lambda z: (z[:-1], z[-1:]))
for x,y in dataset:
    print(x.numpy(), y.numpy())

#Shuffle the data
print("After shuffling")
dataset = dataset.shuffle(buffer_size=10, seed=21)
for x,y in dataset:
    print(x.numpy(), y.numpy())

#Batch the data
print("After batching")
dataset = dataset.batch(batch_size=3).prefetch(1)
for x,y in dataset:
    print("X= ", x.numpy())
    print("Y= ",  y.numpy())


[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]
After shuffling
[0 1 2 3] [4]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[1 2 3 4] [5]
[5 6 7 8] [9]
After batching
X=  [[4 5 6 7]
 [0 1 2 3]
 [2 3 4 5]]
Y=  [[8]
 [4]
 [6]]
X=  [[3 4 5 6]
 [5 6 7 8]
 [1 2 3 4]]
Y=  [[7]
 [9]
 [5]]
